/**
 * Lead Form Options
 * These options match the Apify leads scraper configuration schema
 * Source: backend/packages/lead-watcher/config/lead-form.json
 */

export const BUSINESS_MODEL_OPTIONS = [
  'Product',
  'Services',
  'Solutions',
] as const;

export const COMPANY_EMPLOYEE_SIZE_OPTIONS = [
  '0 - 1',
  '2 - 10',
  '11 - 50',
  '51 - 200',
  '201 - 500',
  '501 - 1000',
  '1001 - 5000',
  '5001 - 10000',
  '10000+',
] as const;

export const SENIORITY_OPTIONS = [
  'Founder',
  'CXO',
  'Chairman',
  'CEO',
  'President',
  'Vice President',
  'Director',
  'Head',
  'Manager',
  'Senior',
  'Junior',
  'Entry Level',
  'Executive',
] as const;

export const FUNCTIONAL_OPTIONS = [
  'Admin',
  'Analytics',
  'Applications',
  'Cloud',
  'Compliance',
  'Controller',
  'Customer Service',
  'Cyber Security',
  'Data Engineering',
  'Devops',
  'Digital',
  'Distribution',
  'Engineering',
  'Finance',
  'Fraud',
  'Hiring',
  'HR',
  'Infrastructure',
  'Inside Sales',
  'IT',
  'Learning',
  'Legal',
  'Marketing',
  'Network Security',
  'Operations',
  'Product Management',
  'Product Security',
  'Production',
  'Purchase',
  'Research',
  'Risk',
  'Sales',
  'Security',
  'Support',
  'Testing',
  'Training',
] as const;

export const REVENUE_OPTIONS = [
  'Less than 1M',
  '1M-10M',
  '11M-100M',
  '101M-500M',
  '501M-1B',
  '1B+',
] as const;

export const FUNDING_TYPE_OPTIONS = [
  'Angel Round',
  'Convertible Note',
  'Corporate Round',
  'Debt Financing',
  'Funding Round',
  'Grant',
  'Initial Coin Offering',
  'Non Equity Assistance',
  'Post',
  'Post-IPO Debt',
  'Post-IPO Equity',
  'Post-IPO Secondary',
  'Pre Seed Round',
  'Private Equity Round',
  'Product Crowdfunding',
  'Secondary Market',
  'Seed Round',
  'Series A',
  'Series B',
  'Series C',
  'Series D',
  'Series E',
  'Series F',
  'Series G',
  'Series H',
  'Series I',
  'Series J',
  'Venture Round',
] as const;

export const INDUSTRY_OPTIONS = [
  'Accommodation Services',
  'Agricultural Chemical Manufacturing',
  'Airlines and Aviation',
  'Armed Forces',
  'Aviation & Aerospace',
  'Cable and Satellite Programming',
  'Chemical Manufacturing',
  'Chemical Raw Materials Manufacturing',
  'Circuses and Magic Shows',
  'Dairy',
  'Defense & Space',
  'Defense and Space Manufacturing',
  'E-learning',
  'Education Management',
  'Entertainment Providers',
  'Gambling Facilities and Casinos',
  'Golf Courses and Country Clubs',
  'Government Relations',
  'Landscaping Services',
  'Laundry and Drycleaning Services',
  'Military and International Affairs',
  'Mobile Gaming Apps',
  'Museums',
  'Operations Consulting',
  'Performing Arts and Spectator Sports',
  'Personal and Laundry Services',
  'Personal Care Services',
  'Pet Services',
  'Photography',
  'Primary and Secondary Education',
  'Professional Organizations',
  'Professional Training and Coaching',
  'Public Policy Offices',
  'Racetracks',
  'Radio and Television Broadcasting',
  'Regenerative Design',
  'Skiing Facilities',
  'Software Development',
  'Sports and Recreation Instruction',
  'Sports Teams and Clubs',
  'Technical and Vocational Training',
  'Telecommunications',
  'Telecommunications Carriers',
  'Textile Manufacturing',
  'Tobacco Manufacturing',
  'Veterinary',
  'Wireless Services',
] as const;

// Major countries sorted by typical priority
export const COUNTRY_OPTIONS = [
  'United States',
  'United Kingdom',
  'Canada',
  'Australia',
  'Germany',
  'France',
  'Netherlands',
  'Ireland',
  'India',
  'Singapore',
  'Japan',
  'Brazil',
  'Mexico',
  'Spain',
  'Italy',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Switzerland',
  'Austria',
  'Belgium',
  'New Zealand',
  'South Africa',
  'United Arab Emirates',
  'Israel',
  'Poland',
  'Portugal',
  'Czech Republic',
  'Argentina',
  'Chile',
  'Colombia',
  'Indonesia',
  'Malaysia',
  'Philippines',
  'Thailand',
  'Vietnam',
  'China',
  'South Korea',
  'Taiwan',
  'Hong Kong S.A.R.',
  // Rest alphabetically
  'Afghanistan',
  'Aland Islands',
  'Albania',
  'Algeria',
  'American Samoa',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antarctica',
  'Antigua And Barbuda',
  'Armenia',
  'Aruba',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Bouvet Island',
  'British Indian Ocean Territory',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Cape Verde',
  'Cayman Islands',
  'Central African Republic',
  'Chad',
  'Christmas Island',
  'Cocos (Keeling) Islands',
  'Comoros',
  'Congo',
  'Congo The Democratic Republic Of The',
  'Cook Islands',
  'Costa Rica',
  'Croatia (Hrvatska)',
  'Cuba',
  'Cyprus',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Faroe Islands',
  'Fiji',
  'Fiji Islands',
  'French Guiana',
  'French Polynesia',
  'French Southern Territories',
  'Gabon',
  'Gambia',
  'Georgia',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernsey and Alderney',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Heard and McDonald Islands',
  'Honduras',
  'Hungary',
  'Iceland',
  'Iran',
  'Iraq',
  'Ivory Coast',
  'Jamaica',
  'Jersey',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Korea North',
  'Korea South',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macau S.A.R.',
  'Macedonia',
  'Madagascar',
  'Malawi',
  'Maldives',
  'Mali',
  'Malta',
  'Man (Isle of)',
  'Marshall Islands',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'New Caledonia',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue',
  'Norfolk Island',
  'North Korea',
  'Northern Mariana Islands',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestinian Territory Occupied',
  'Panama',
  'Papua new Guinea',
  'Paraguay',
  'Peru',
  'Pitcairn Island',
  'Puerto Rico',
  'Qatar',
  'Reunion',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Helena',
  'Saint Kitts And Nevis',
  'Saint Lucia',
  'Saint Pierre and Miquelon',
  'Saint Vincent And The Grenadines',
  'Saint-Barthelemy',
  'Saint-Martin (French part)',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Georgia',
  'South Sudan',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Svalbard And Jan Mayen Islands',
  'Swaziland',
  'Syria',
  'Tajikistan',
  'Tanzania',
  'Timor-Leste',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad And Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks And Caicos Islands',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United States Minor Outlying Islands',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City State (Holy See)',
  'Venezuela',
  'Virgin Islands (British)',
  'Virgin Islands (US)',
  'Wallis And Futuna Islands',
  'Western Sahara',
  'Yemen',
  'Zambia',
  'Zimbabwe',
] as const;

// US States for person/company state filtering
export const US_STATE_OPTIONS = [
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
  'District of Columbia',
] as const;

// Canadian provinces
export const CANADA_PROVINCE_OPTIONS = [
  'Alberta',
  'British Columbia',
  'Manitoba',
  'New Brunswick',
  'Newfoundland and Labrador',
  'Northwest Territories',
  'Nova Scotia',
  'Nunavut',
  'Ontario',
  'Prince Edward Island',
  'Quebec',
  'Saskatchewan',
  'Yukon',
] as const;

// Types
export type BusinessModel = typeof BUSINESS_MODEL_OPTIONS[number];
export type CompanyEmployeeSize = typeof COMPANY_EMPLOYEE_SIZE_OPTIONS[number];
export type Seniority = typeof SENIORITY_OPTIONS[number];
export type Functional = typeof FUNCTIONAL_OPTIONS[number];
export type Revenue = typeof REVENUE_OPTIONS[number];
export type FundingType = typeof FUNDING_TYPE_OPTIONS[number];
export type Industry = typeof INDUSTRY_OPTIONS[number];
export type Country = typeof COUNTRY_OPTIONS[number];
